### PR TITLE
Changed ID as .download is considered to be a file by Finder

### PR DESCRIPTION
**Pull request by seansgm**
Although this works fine in a shell, Finder thinks that .download is a file not a directory.  Whilst there I banged out a pkg at the same time.

### CODE REVIEW

**Comment by seansgm** [comment]
Whilst testing I ditched the request_headers.  Didn't put it back, but should work without!

**Comment by gregneagle** [comment]
Changing a recipe identifier will break everyone's child recipes or recipe overrides based on the recipe. Weigh carefully whether this change is worth the potential disruption and confusion.

**Comment by seansgm** [comment]
Yeah, the Munki recipe will also need to be changed to reflect, but as I don't use Munki and can't test, I didn't submit that change.  (although I guess I should have anyway and that could have been reviewed first).

I'm happy using Terminal, but I don't think it should be left as is though, since Finder incorrectly shows this as a file and you can't navigate to any of the files.

**Comment by timsutton** [comment]
It's worth considering who else might be using the download recipe, though. This would typically be 1) someone who overrides the recipe, or 2) someone who makes a child recipe (like a .jss recipe), which others may have then overridden locally. In both of these cases there will be a break in the chain from the child to the top-level parent.

**Comment by hansen-m** [comment]
I have a .bigfix child recipe for this one. My typical workflow for an issue like this is noticing it is broken in the logs and after a few days days in consistent failures I will investigate it by looking at the recent commits and eventually fix it. Overall maybe about 10min or less of total human time spent. But multiple that by the number of admins with overrides or child recipes and compare to the value added by making the change.

**Comment by seansgm** [comment]
You mean everyone using each recipe for their production isn't 'Watching' them and get informed with the details when a change like this might happen ;)  No worries, instead each new adopter can spend 10 minutes asking themselves why they have a file instead and then realise that actually it isn't a file and just realise everything is okay after all.

**Comment by gregneagle** [comment]
That's kind of the entire point here: this is not a change that unambiguously improves things. It fixes one problem while temporarily creating another. it's up to swy to decide if the problem being solved is worth the (temporary) pain.

**Comment by swy** [comment]
While I acknowledge that a .download file is not the optimal output (this was my first recipe) changing it will have downstream effects on others, including hansen-m.  As there's little reason to be navigating the autopkg cache output via the Finder, and if needed a right-click and Show Package Contents allows access to the content, I think implementing this change will cause more issues than provide solutions.
I will be adding the .pkg recipe to the repo- thanks.

**Comment by seansgm** [comment]
Yeah, I went through the same thought process.  I don't usually use Finder, except when adding new recipes.  I can run Terminal and whilst everything is being created I can see them actively appear in Terminal.  Of course I initially thought I'd done something wrong (which is good as it shows how much I trust the tool), but then after a couple of attempts and going through the file, looking at the logs, I suddenly realised I didn't have a failed download and it was indeed a directory full of the required files.  I decided to offer the change, as I felt that this would indeed fix it, as oppose to it being there forever.  Don't forget to change the parent in the pkg if you don't take the download recipe.

**Comment by seansgm** [comment]
On a related note, one for Greg or Tim, you can't override RECIPE_CACHE_DIR.... can you?

**Pull request merged**
